import java.util.List;

public class AdminReport implements Report {
    private Report decoratedReport;
    private User user;

    public AdminReport(Report report, User user) {
        this.decoratedReport = report;
        this.user = user;
    }

    @Override
    public void generateReport() {
        if (!(user instanceof Admin)) {
            System.out.println("Error! Only admins can generate reports.");
            return;
        }

        // Først kør den normale rapport
        decoratedReport.generateReport();

        // Udskriv systemdata
        System.out.println("\n --- ADMIN REPORT ---");

        // Brugerliste
        UserAdmin ua = UserAdmin.getInstance();
        System.out.println("\nUsers in the system:");
        List<User> users = ua.getAllUsers();
        for (User u : users) {
            System.out.println(" - " + u.getName() + " (" + (u instanceof Admin ? "Admin" : "User") + ")");
        }

        // Eventliste
        EventManager em = EventManager.getInstance();
        List<Event> events = em.getEvents();

        System.out.println("\n Events:");
        if (events.isEmpty()) {
            System.out.println(" - No events added yet.");
        } else {
            for (Event e : events) {
                System.out.println(" - " + e.getTitle() + " (" + e.getDate() + " at " + e.getPlace() + ")");
                if (e.getParticipants().isEmpty()) {
                    System.out.println("   No participants added yet.");
                } else {
                    System.out.println("   Participants:");
                    for (User p : e.getParticipants()) {
                        System.out.println("    - " + p.getName());
                    }
                }
            }
        }

        System.out.println("\nReport generated by admin: " + user.getName());
        System.out.println("-----------------------------\n");
    }

}
